name = "willyshop"
compatibility_date = "2024-09-25"
main = "src/index.js"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "willy-store-db"
database_id = "b8bd8fb8-eaee-40c6-92ed-d0fc1b0ac1c3"
